// M8.8 — Deterministic, isomorphic renderer for the project-root CLAUDE.md.
//
// Pure: same input → same bytes. Called from both the Electron main process
// (after UI mutations) and the MCP server (after tool-driven writes), so the
// output must not depend on Date.now(), process env, or Map iteration order.
//
// Companion files are intentionally slim. The hook index + MCP tools
// carry the real workspace-specific context when the task signals need it.
//
// The promoted_rules section is appended when a PromotedRulesBundle is
// provided. The splice uses the same anchor convention as the other clients.

import type { WorkspaceOverviewNode } from "./tools/tree.js";
import { splicePromotedRulesSection } from "./client-renderers/promoted-rules-section.js";
import type { PromotedRulesBundle } from "./client-renderers/types.js";

export interface RootRule {
  id: string;
  name: string;
  scope_type: string;
  priority: string;
}

export interface RootSkill {
  id: string;
  name: string;
  description: string | null;
  source: string;
}

export interface RootMemory {
  id: string;
  title: string;
  preview: string;
}

export interface HotPathEntry {
  path: string;
  change_count: number;
}

/** Activity log entry for CLAUDE.md rendering. */
export interface RecentActivityEntry {
  domain: string;
  action: string;
  task_summary: string;
  created_at: string; // ISO date (YYYY-MM-DD)
}

export interface ProjectClaudeMdInput {
  workspaceName: string;
  rootContext: {
    memories: RootMemory[];
    rules: RootRule[];
    skills: RootSkill[];
  };
  overview: WorkspaceOverviewNode[];
  /** Retained in the input contract; not rendered into slim companions. */
  hotPaths?: HotPathEntry[];
  /** Retained in the input contract; not rendered into slim companions. */
  recentActivities?: RecentActivityEntry[];
  /** Promoted rules bundle; when present, appended as a dedicated section. */
  promotedRules?: PromotedRulesBundle;
}

const BANNER =
  "<!-- managed by Pathrule — do not edit this file manually. " +
  "Cloud state is authoritative. Local edits are overwritten. -->";

const INSTRUCTIONS = [
  "# Pathrule Workspace",
  "",
  "Pathrule is this workspace's shared memory, rule, and skill layer for AI agents.",
  "Use it as a smart reminder system, not a full-context dump.",
  "",
  "## Context Policy",
  "",
  "- Pathrule is the first knowledge layer for this workspace. Use hook context first: metadata, relevant rule titles, path reminders, and filename/skill matches.",
  "- `::skill-name` is a hard gate: use the exact injected skill; if missing, stop and resolve it through Pathrule/MCP before file edits.",
  '- Do not reflexively call `pathrule_get_context` before every small known-path code task. For discovery, inventory, architecture, recent activity, or "list/show/find/where/which" prompts (Turkish: listele, göster, bul, nerede, hangi, neler), call it before any grep/read/fallback when hook context is missing, ambiguous, or stale.',
  "- Hook silence on a topic does not mean Pathrule has no relevant memory/rule. For discovery/inventory/architecture questions, call `pathrule_get_context` first; fall back to files, git, or general knowledge only after Pathrule returns nothing relevant.",
  "- When calling `pathrule_get_context`, pass `cwd`, `user_intent`, and `omit_protocol: true`; this file already contains the protocol.",
  "- Read full bodies with `pathrule_read_memory`, `pathrule_read_rule`, or `pathrule_read_skill` when a surfaced title/id is relevant.",
  "- Treat existing local edits as protected user/team work: inspect overlaps, never revert unrelated changes, and keep edits scoped.",
  "- Obey every surfaced rule. If a user request conflicts with a Pathrule rule, warn before taking action.",
  "",
  "## Writes",
  "",
  "- Pathrule cloud is the source of truth. Do not create local memory files such as `MEMORY.md` or `~/.claude/memory/`.",
  "- Use path-first writes for lasting project knowledge: `pathrule_write_memory`, `pathrule_write_rule`, and `pathrule_write_skill` take the most specific workspace-relative `node_path`.",
  "- Do not edit materialized local Pathrule files as the source of truth. This includes `.codex/skills/**/SKILL.md`, `.claude/skills/**`, rendered companion files, and synced skill/memory/rule files. Read only for orientation; create/update cloud records with the Pathrule MCP write/update tools.",
  "- After any file-modifying response, call `pathrule_log_activity` once with domain, action, scope, subjects, files_touched, and a concise task_summary.",
  "",
].join("\n");

/**
 * Render the project-level CLAUDE.md. Pure; deterministic. Caller is
 * responsible for writing to disk and upserting the snapshot row.
 *
 * When `input.promotedRules` is provided, the promoted_rules section is
 * appended using the same anchor convention as the other client renderers.
 */
export function renderProjectClaudeMd(input: ProjectClaudeMdInput): string {
  let body = [BANNER, "", INSTRUCTIONS].join("\n").replace(/\n{3,}/g, "\n\n");
  body = body.endsWith("\n") ? body : `${body}\n`;

  // Splice in promoted rules section.
  if (input.promotedRules) {
    body = splicePromotedRulesSection(body, input.promotedRules, {
      headingLevel: 2,
      includeAttribution: true,
    });
  }

  return body;
}
